### ISSUE TITLE
Memory functionality

### ISSUE THREAD

**Issue by 7ap** [hax-rs/hax#1]
- Read & write process memory
- Universal? (same function signature for internal/external, change depending on feature flag in use)
- Bulk reading? (read entire struct in with one call)
- Caching values? (only read an address once and cache result)

**Comment by 7ap** [comment]
I think that using [memlib](https://github.com/rmccrystal/memlib-rs) as our interface to memory would be really good. Their implementation is great and I think with a bit of wrapping and (perhaps) some new macros to make memory introspection easier it would be perfect!

(permission from @rmccrystal)

![image](https://user-images.githubusercontent.com/109433659/204888823-b3ad69a4-bd82-4dcf-9cbb-89dc543f65f9.png)

**Comment by not-matthias** [comment]
It's important that we focus on making it easily extendable. 

**Example:** If you want to target a game with encrypted pages, you need to find a way to decrypt it before reading. So should be able to create your own implementation and plug it into the system: 
```
struct EncryptedMemory {} 

impl MemoryRead for EncryptedMemory { ... }
impl MemoryWrite for EncryptedMemory { ... }
```

**Comment by rmccrystal** [comment]
> Agreed. I also think due to the nature of `hax:::main` and trying to be as 'cross-platform' as possible, we should definitely try to implement the "universal" read/write. Is it possible to write abstractions on top of memlib to do that?
> 
> **Example**: If we wanted to read an address, both the external and internal read memory calls would be the same.

Yes, this is possible using either dynamic dispatch (`dyn memlib::MemoryRead + memlib::MemoryWrite`) or having a type alias for your memory API which changes based on your feature flags. For example:
```rust
// Each Api type alias implements the same traits
#[cfg(feature="external")]
pub type Api = ExternalApi; // implements MemoryRead and MemoryWrite
#[cfg(feature="internal")]
pub type Api = InternalApi; // implements MemoryRead and MemoryWrite
```
